#!/bin/sh
# Stops the commit if there are any formatting, linting, or test issues

set -e

# ANSI color codes
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color



echo "${BLUE}Running Dart Format...${NC}"
echo  " "
dart format --set-exit-if-changed lib test

echo "${BLUE}Running Flutter Analyzer...${NC}"
echo  " "
flutter analyze lib test

echo "${BLUE}Running dart fix --apply...${NC}"
echo  " "
dart fix --apply

