# on:
#   pull_request:
#     branches:
#       - main
#       - staging
#       - production
#   push:
#     branches:
#       - main
#       - staging
#       - production

# name: "Checking Formatting"

# jobs:
#   build:
#     name: Format & Build
#     runs-on: macos-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Java
#         uses: actions/setup-java@v3
#         with:
#           distribution: "temurin"
#           java-version: "17"

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.24.2"
#           channel: stable

#       - name: Cache Flutter Pub Dependencies
#         uses: actions/cache@v3
#         with:
#           path: ~/.pub-cache
#           key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-pub-cache-

#       - name: Flutter Clean
#         run: flutter clean

#       - name: Flutter Pub Get
#         run: flutter pub get

#       - name: Flutter Analyze
#         run: flutter analyze --fatal-infos

#       - name: Dart Format
#         run: dart format . --set-exit-if-changed

#       - name: Dart Fix
#         run: dart fix --apply

#       - name: Flutter Build APK
#         run: flutter build apk
